#!/bin/sh

RCFILE=openstack-setup.rc

if [ -e ${RCFILE} ]; then
 . $RCFILE
fi

if [ -n "$DB_ROOT_PW" ]; then
 DBPW="--rootpw $DB_ROOT_PW"
fi

openstack-db -y --init --service nova --rootpw "$DBPW"

if [ "$ENABLE_CINDER" = "1" ] ; then
      # Change nova configuration to use cinder
      openstack-config --set /etc/nova/nova.conf DEFAULT volume_api_class nova.volume.cinder.API
      # The following is the default apis with 'osapi_volume' removed
      openstack-config --set /etc/nova/nova.conf DEFAULT enabled_apis ec2,osapi_compute,metadata
fi 


echo "======= Enabling the services ======"

for svc in qpidd libvirtd ; do
    chkconfig $svc on
done
for svc in api objectstore compute network scheduler cert; do
    chkconfig openstack-nova-$svc on
done

echo "======= Starting the services ======"

for svc in qpidd libvirtd; do
    service $svc start
done
for svc in api objectstore compute network scheduler cert; do
    service openstack-nova-$svc start
done

# Change nova configuration to use keystone
openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
if [ "$os_dist" = 'essex' ]; then
  openstack-config --set /etc/nova/api-paste.ini filter:authtoken admin_tenant_name service
  openstack-config --set /etc/nova/api-paste.ini filter:authtoken admin_user nova
  openstack-config --set /etc/nova/api-paste.ini filter:authtoken admin_password $NOVA_SERVICE_PASSWORD
else # >= folsom
  openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_tenant_name service
  openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_user nova
  openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_password $NOVA_SERVICE_PASSWORD
fi
for svc in api compute; do
    service openstack-nova-$svc restart
done


