#!/bin/sh

RCFILE=openstack-setup.rc

if [ -e ${RCFILE} ] ; then
 . $RCFILE
fi

if [ -e "$SETUP_UTILS" ] ; then
    . ${SETUP_UTILS}
else
    echo "Missing Setup Utils"
fi


openstack-keystone-setup
openstack-glance-setup
openstack-nova-setup
openstack-cinder-setup
openstack-horizon-setup
openstack-swift-setup

save_runtime $RUNTIME_RC
