#!/bin/sh
RCFILE=${1:-"openstack-setup.rc"}

if [ -e ${RCFILE} ]; then
 . $RCFILE
else
 echo "Missing ${RCFILE}"
 exit 1
fi



if [ -n "$DB_ROOT_PW" ]; then
 DBPW="--rootpw $DB_ROOT_PW"
fi

echo "======= Setting up Swift ======"

setup_swift(){
  # edit default config
  openstack-config --set /etc/swift/proxy-server.conf filter:authtoken admin_tenant_name service
  openstack-config --set /etc/swift/proxy-server.conf filter:authtoken admin_user swift
  openstack-config --set /etc/swift/proxy-server.conf filter:authtoken admin_password servicepass
  openstack-config --set /etc/swift/swift.conf swift-hash swift_hash_path_suffix $(openssl rand -hex 10)

  ## below is down in keystone-sample-data
  # swift_keystone_sample_data

  # Create ringfiles and storage devices
  swift-ring-builder /etc/swift/account.builder create 12 3 1
  swift-ring-builder /etc/swift/container.builder create 12 3 1
  swift-ring-builder /etc/swift/object.builder create 12 3 1
  for zone in 1 2 3 4; do
    truncate /var/tmp/swift-storage-$zone --size 5G
    DEVICE=$(losetup --show -f  /var/tmp/swift-storage-$zone)
    mkfs.ext4 -I 1024 $DEVICE
    mkdir -p /srv/node/device$zone
    mount -o noatime,nodiratime,nobarrier,user_xattr $DEVICE /srv/node/device$zone
    swift-ring-builder /etc/swift/account.builder add z$zone-127.0.0.1:6002/device$zone 100
    swift-ring-builder /etc/swift/container.builder add z$zone-127.0.0.1:6001/device$zone 100
    swift-ring-builder /etc/swift/object.builder add z$zone-127.0.0.1:6000/device$zone 100
  done
  swift-ring-builder /etc/swift/account.builder rebalance
  swift-ring-builder /etc/swift/container.builder rebalance
  swift-ring-builder /etc/swift/object.builder rebalance

  # Make sure swift owns the ring file
  chown -R swift:swift /etc/swift/*gz /srv/node

  # Start the services
  service memcached start
  chkconfig memcached on
  service openstack-swift-proxy start
  chkconfig openstack-swift-proxy on
  for ringtype in account container object; do
    service openstack-swift-$ringtype start
    chkconfig openstack-swift-$ringtype on
    for service in replicator updater auditor; do
      if [ $ringtype != 'account' ] || [ $service != 'updater' ]; then
        swift-init $ringtype-$service start
      fi
    done
  done

}

# We can only setup Swift for packages that contain example config files
[ -e /etc/swift/proxy-server.conf ] && setup_swift


