#!/bin/sh

RCFILE=${1:-"openstack-setup.rc"}

if [ -e ${RCFILE} ]; then
 . $RCFILE
else
 echo "Missing ${RCFILE}"
 exit 1
fi

if [ -n "$DB_ROOT_PW" ]; then
 DBPW="--rootpw $DB_ROOT_PW"
fi


# Allow httpd (horizon) to connect to other services
setsebool -P httpd_can_network_connect=on
setsebool -P httpd_tmp_exec=on
service httpd restart


