#!/bin/sh

RCFILE=${1:-"openstack-setup.rc"}

if [ -e ${RCFILE} ] ; then
 . $RCFILE
else
 echo "Missing $RCFILE"
 exit 1
fi

[ -n "$ENABLE_KEYSTONE" ]   && openstack-keystone-setup $RCFILE
[ -n "$ENABLE_GLANCE" ]     && openstack-glance-setup   $RCFILE
[ -n "$ENABLE_NOVA" ]       && openstack-nova-setup     $RCFILE
[ -n "$ENABLE_CINDER" ]     && openstack-cinder-setup   $RCFILE
[ -n "$ENABLE_HORIZON" ]    && openstack-horizon-setup  $RCFILE
[ -n "$ENABLE_SWIFT" ]      && openstack-swift-setup    $RCFILE

openstack-status
