#!/bin/sh

RCFILE=${1:-"openstack-setup.rc"}

if [ -e ${RCFILE} ]; then
 . $RCFILE
else
 echo "Missing ${RCFILE}"
 exit 1
fi

if [ -n "$DB_ROOT_PW" ]; then
 DBPW="--rootpw $DB_ROOT_PW"
fi

. ${SETUP_UTILS}
detect_distro

openstack-db -y --init --service cinder --rootpw "$DBPW"

for svc in api scheduler; do
    chkconfig openstack-cinder-$svc on
done

for svc in api scheduler; do
    service openstack-cinder-$svc start
done

openstack-config --set /etc/cinder/cinder.conf DEFAULT auth_strategy keystone
openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_tenant_name service
openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_user cinder
openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_password $CINDER_SERVICE_PASSWORD

# Start the services
# Note volume requires the cinder-volumes volume group
# to be available, so we don't enable that by default
for svc in api scheduler; do
    service openstack-cinder-$svc restart
done



## Fixes for RHEL 6.x <= 6.3
if [ "$DISTRO" = 'el' ] ; then
    if [ "$DISTRO_VER" -eq '6' ] ; then
      if [ "$DISTRO_REL" -le '3' ] ; then
        
        ## as per comment in /etc/tgt/conf.d/cinder.conf
        ## while not flexible or smart - it should do the trick
        grep -F 'include /etc/cinder/volumes/*' /etc/tgt/targets.conf || \
         sed -i '0 i ##OPENSTACK-SETUP: \
    include /etc/cinder/volumes/* \
    ' /etc/tgt/targets.conf
      fi
    fi
fi

service tgtd restart
chkconfig tgtd on
service openstack-cinder-volume start
chkconfig openstack-cinder-volume on

